"""Initial migration

Revision ID: 691bc97d7a18
Revises:
Create Date: 2025-11-04 20:17:21.535968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
from db.models.decorator.type_decorator import IntEnumType
from src.models.enum.tariff import Tariff


# revision identifiers, used by Alembic.
revision: str = '691bc97d7a18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact')
    )
    op.create_table('gift',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_contact', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_expired', sa.DateTime(), nullable=False),
    sa.Column('tariff', IntEnumType(Tariff), nullable=False),
    sa.Column('has_sauna', sa.Boolean(), nullable=False),
    sa.Column('has_additional_bedroom', sa.Boolean(), nullable=False),
    sa.Column('has_secret_room', sa.Boolean(), nullable=False),
    sa.Column('is_paymented', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('tariff', IntEnumType(Tariff), nullable=False),
    sa.Column('has_photoshoot', sa.Boolean(), nullable=False),
    sa.Column('has_sauna', sa.Boolean(), nullable=False),
    sa.Column('has_white_bedroom', sa.Boolean(), nullable=False),
    sa.Column('has_green_bedroom', sa.Boolean(), nullable=False),
    sa.Column('has_secret_room', sa.Boolean(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.Column('is_date_changed', sa.Boolean(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('is_prepaymented', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('feedback_submitted', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('prepayment_price', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.Column('wine_preference', sa.String(), nullable=True),
    sa.Column('transfer_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('gift')
    op.drop_table('user')
    # ### end Alembic commands ###
