"""Add completed_bookings to users

Revision ID: 8be7e628f1ca
Revises: d7cf40ae784b
Create Date: 2025-11-05 16:49:43.050552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8be7e628f1ca"
down_revision: Union[str, None] = "d7cf40ae784b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "completed_bookings", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "completed_bookings")
    # ### end Alembic commands ###
