"""add comment and is_paid columns to bookings

Revision ID: 8e261b9824f5
Revises: 
Create Date: 2025-03-28 11:12:25.693384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e261b9824f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('prepayment_price', sa.Float(), nullable=False, server_default=sa.text("80.0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'prepayment_price')
    # ### end Alembic commands ###
