"""Add promocode table and booking promocode_id

Revision ID: e351ee0a0cb0
Revises: 523a953b48b2
Create Date: 2025-11-07 22:51:41.003457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e351ee0a0cb0"
down_revision: Union[str, None] = "523a953b48b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocode",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("discount_percentage", sa.Float(), nullable=False),
        sa.Column("applicable_tariffs", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.add_column(sa.Column("promocode_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_booking_promocode", "promocode", ["promocode_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_constraint("fk_booking_promocode", type_="foreignkey")
        batch_op.drop_column("promocode_id")
    op.drop_table("promocode")
    # ### end Alembic commands ###
