from enum import Enum


class BookingStep(Enum):
    TARIFF = "TARIFF"
    FIRST_BEDROOM = "FIRST_BEDROOM"
    SECOND_BEDROOM = "SECOND_BEDROOM"
    SAUNA = "SAUNA"
    PHOTOSHOOT = "PHOTOSHOOT"
    SECRET_ROOM = "SECRET_ROOM"
    START_DATE = "START_DATE"
    START_TIME = "START_TIME"
    FINISH_DATE = "FINISH_DATE"
    FINISH_TIME = "FINISH_TIME"
    COMMENT = "COMMENT"
    PROMOCODE = "PROMOCODE"
    NUMBER_GUESTS = "NUMBER_GUESTS"
    CONFIRM_BOOKING = "CONFIRM_BOOKING"
    CONTACT = "CONTACT"
    PAY = "PAY"
    FINISH = "FINISH"
    WINE_PREFERENCE = "WINE_PREFERENCE"
    TRANSFER_ADDRESS = "TRANSFER_ADDRESS"
