from enum import Enum
from token import NUMBER

class BookingStep(Enum):
    TARIFF = "TARIFF"
    FIRST_BEDROOM = "FIRST_BEDROOM"
    SECOND_BEDROOM = "SECOND_BEDROOM"
    SAUNA = "SAUNA"
    PHOTOSHOOT = "PHOTOSHOOT"
    SECRET_ROOM = "SECRET_ROOM"
    START_DATE = "START_DATE"
    START_TIME = "START_TIME"
    FINISH_DATE = "FINISH_DATE"
    FINISH_TIME = "FINISH_TIME"
    COMMENT = "COMMENT"
    NUMBER_GUESTS = "NUMBER_GUESTS"
    CONFIRM_BOOKING = "CONFIRM_BOOKING" 
    CONTACT = "CONTACT" 
    PAY = "PAY" 
    FINISH = "FINISH" 