from telegram.ext import ConversationHandler

# Основные команды
BACK = "BACK"
CONFIRM = "CONFIRM"
END = ConversationHandler.END

# Тип меню
MENU = "MENU"
BOOKING = "BOOKING"
CANCEL_BOOKING = "CANCEL_BOOKING"
CHANGE_BOOKING_DATE = "CHANGE_BOOKING_DATE"
AVAILABLE_DATES = "AVAILABLE_DATES"
QUESTIONS = "QUESTIONS"
PRICE = "PRICE"
GIFT_CERTIFICATE = "GIFT_CERTIFICATE"
SUBSCRIPTION = "SUBSCRIPTION"
USER_BOOKING = "USER_BOOKING"

# Отмена бронирования
CANCEL_BOOKING_VALIDATE_USER = "CANCEL_BOOKING_VALIDATE_USER"

# Изменение даты бронирования
CHANGE_BOOKING_DATE_VALIDATE_USER = "CHANGE_BOOKING_DATE_VALIDATE_USER"

# Подарочные сертификаты
SET_USER = "SET_USER"
GIFT_PHOTO_UPLOAD = "PHGIFT_PHOTO_UPLOADOTO_UPLOAD"
GIFT_VALIDATE_USER = "GIFT_VALIDATE_USER"

# Абонемент
SUBSCRIPTION_VALIDATE_USER = "SUBSCRIPTION_VALIDATE_USER"
SUBSCRIPTION_PHOTO_UPLOAD = "SUBSCRIPTION_PHOTO_UPLOAD"

# Бронирование
BOOKING_VALIDATE_USER = "BOOKING_VALIDATE_USER"
BOOKING_PHOTO_UPLOAD = "BOOKING_PHOTO_UPLOAD"
BOOKING_VALIDATE_USER = "BOOKING_VALIDATE_USER"
BOOKING_PHOTO_UPLOAD = "BOOKING_PHOTO_UPLOAD"
BOOKING_WRITE_CODE = "BOOKING_WRITE_CODE"
BOOKING_COMMENT = "BOOKING_COMMENT"
SKIP = "SKIP"
CASH_PAY = "CASH_PAY"
BOOKING_VALIDATE_USER = "BOOKING_VALIDATE_USER"

# Бронирование пользователя
USER_BOOKING_VALIDATE_USER = "USER_BOOKING_VALIDATE_USER"

# Выбор даты и времени
HOURS_CALLBACK = "HOURS-CALLBACK"
CALENDAR_CALLBACK = "CALENDAR-CALLBACK"
ACTION = "ACTION"
IGNORE = "IGNORE"

# Admin
SET_PASSWORD = "SET_PASSWORD"
CHANGE_BOOKING_ADMIN = "CHANGE_BOOKING_ADMIN"
SELECT_MENU_ADMIN = "SELECT_MENU_ADMIN"
UPDATE_BOOKING = "UPDATE_BOOKING"
CHANGE_PREPAYMENT_PRICE = "CHANGE_PREPAYMENT_PRICE"
SET_ADMIN_COMMENT = "SET_ADMIN_COMMENT"
CHANGE_PRICE = "CHANGE_PRICE"